name: miro
description: KIRA blockchain explorer
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.28.1

environment:
  sdk: ">=3.1.3"
  flutter: "^3.13.6"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # AutoRoute is a declarative routing solution, where everything needed for navigation is automatically generated for you.
  # https://pub.dev/packages/auto_route
  auto_route: ^7.8.3

  # This is a simple Service Locator for Dart and Flutter projects
  # https://pub.dev/packages/get_it
  get_it: ^7.6.4

  # A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData,
  # Request Cancellation, File downloading, Timeout etc.
  # https://pub.dev/packages/dio
  dio: ^5.3.3

  # A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  # https://pub.dev/packages/equatable
  equatable: ^2.0.5

  # Fast, Enjoyable & Secure NoSQL Database
  # https://pub.dev/packages/hive
  hive: ^2.2.3

  # Extension for Hive. Makes it easier to use Hive in Flutter apps.
  # https://pub.dev/packages/hive_flutter
  hive_flutter: ^1.1.0

  # Small, easy to use and extensible logger which prints beautiful logs.
  # https://pub.dev/packages/logger
  logger: ^2.0.2+1

  # Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.3

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  # https://pub.dev/packages/intl
  intl: ^0.18.1

  # Flutter package that allows setting the web app URL strategy with a single line of code.
  # https://pub.dev/packages/url_strategy
  url_strategy: ^0.2.0

  # A flutter package that helps copy text to clipboard and paste from clipboard.
  # https://pub.dev/packages/clipboard
  clipboard: ^0.1.3

  ##################################
  ####### Crypto libraries #########
  ##################################

  # Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
  # https://pub.dev/packages/bip39
  bip39: ^1.0.6

  # A BIP32 (https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) compatible library for Flutter writing by Dart.
  # https://pub.dev/packages/bip32
  bip32: ^2.0.0

  # A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library.
  # https://pub.dev/packages/pointycastle
  pointycastle: ^3.7.3

  # Easy hexadecimal conversion using dart:convert API.
  # https://pub.dev/packages/hex
  hex: ^0.2.0

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  # https://pub.dev/packages/crypto
  crypto: ^3.0.3

  # A set of high-level APIs over PointyCastle for two-way cryptography.
  # https://pub.dev/packages/encrypt
  encrypt: ^5.0.3

  # Library implementing Bitcoins BIP173 (Bech32 encoding) specification in a Flutter friendly fashion
  # https://pub.dev/packages/bech32
  bech32: ^0.2.2

  # The decimal package allows you to deal with decimal numbers without losing precision.
  # https://pub.dev/packages/decimal
  decimal: ^2.3.3

  ##################################
  ######### UI libraries ###########
  ##################################

  # A drag-and-drop Flutter plugin (Web only).
  # https://pub.dev/packages/flutter_dropzone
  flutter_dropzone: ^3.0.6

  # Toast Library for Flutter, Easily create toast messages in single line of code
  # https://pub.dev/packages/fluttertoast
  fluttertoast: ^8.2.2

  # QR.Flutter is a Flutter library for simple and fast QR code rendering via a Widget or custom painter.
  # https://pub.dev/packages/qr_flutter
  qr_flutter: ^4.1.0

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.7

  # This is the Dart/Flutter implementation of the Jdenticon project. Jdenticon is a quick and easy to use library for generating highly recognizable identicons using SVG.
  # https://pub.dev/packages/jdenticon_dart
  jdenticon_dart: ^2.0.0

  # A package that allows you to use a native file explorer to pick single or multiple absolute file paths, with extension filtering support
  # https://pub.dev/packages/file_picker
  file_picker: ^5.5.0

  # A Flutter plugin for controlling the camera. Supports previewing the camera feed,
  # capturing images and video, and streaming image buffers to Dart.
  # https://pub.dev/packages/camera
  camera: ^0.10.5+5

  # A Flutter plugin for getting information about and controlling the camera on Web.
  # https://pub.dev/packages/camera_web
  camera_web: ^0.3.2+3

  # A common platform interface for the camera plugin.
  # https://pub.dev/packages/camera_platform_interface
  camera_platform_interface: ^2.5.2

  # A collection of loading indicators animated with flutter. Heavily inspired by @tobiasahlin's SpinKit.
  # https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: ^5.2.0

  # A json preview package that has a not bad performance. lazy load json tree node that cause less jank. 
  # Support display large list json data like chrome dev tool.
  # https://pub.dev/packages/json_view
  json_view: ^0.4.2
  
  # RFC4122 (v1, v4, v5) UUID Generator and Parser for all Dart platforms (Web, VM, Flutter)
  # https://pub.dev/packages/uuid
  uuid: ^4.1.0
  
  # A set of useful sliver tools that are missing from the flutter framework
  # https://pub.dev/packages/sliver_tools
  sliver_tools: ^0.2.12

  # Regexes to match and extract information from URLs of social media profiles
  # https://pub.dev/packages/url_recognizer
  url_recognizer: ^0.0.2+2

  # A lightweight and customizable calendar picker based on Flutter CalendarDatePicker,
  # with support for single date picker, range picker and multi picker.
  # https://pub.dev/packages/calendar_date_picker2
  calendar_date_picker2: ^0.5.2

  # An extensible library that provides the functionality of the parsing strings in different formats to extract dates.
  # https://pub.dev/packages/datify
  datify: ^1.1.3

  # Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.3.0

  # A multi-directional tooltip used to display any content with inbuilt support for list views
  # https://pub.dev/packages/just_the_tooltip
  just_the_tooltip:
    git:
      url: https://github.com/CandyLabsIT/just_the_tooltip.git
      ref: dp-bugfix/target-information

  cryptography_utils:
    git:
      url: git@github.com:snggle/cryptography_utils.git
      ref: dp-feature/public-address-encoders

dev_dependencies:
  # AutoRoute is a declarative routing solution, where everything needed for navigation is automatically generated for you.
  # https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^7.3.1

  # A build system for Dart code generation and modular compilation.
  # https://pub.dev/packages/build_runner
  build_runner: ^2.4.6

  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  # https://pub.dev/packages/hive_generator
  hive_generator: ^2.0.1

  # A simple to use mocking package for Dio intended to be used in tests. It provides various types and methods to declaratively mock request-response communication.
  # https://pub.dev/packages/http_mock_adapter
  http_mock_adapter: ^0.6.0

  # A testing library which makes it easy to test blocs. Built to be used with the bloc state management package.
  # https://pub.dev/packages/bloc_test
  bloc_test: ^9.1.0

  # flutter_lints: ^1.0.4

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/icons/

  fonts:
    - family: IconsFont
      fonts:
        - asset: assets/fonts/IconsFont.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
