// Mocks generated by Mockito 5.4.4 from annotations
// in miro/test/unit/shared/models/wallet/address/cosmos_wallet_address_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:miro/blocs/generic/network_module/a_network_module_event.dart'
    as _i6;
import 'package:miro/blocs/generic/network_module/network_module_bloc.dart'
    as _i5;
import 'package:miro/blocs/generic/network_module/network_module_state.dart'
    as _i4;
import 'package:miro/shared/models/tokens/token_default_denom_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCompleter_0<T> extends _i1.SmartFake implements _i2.Completer<T> {
  _FakeCompleter_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenDefaultDenomModel_1 extends _i1.SmartFake
    implements _i3.TokenDefaultDenomModel {
  _FakeTokenDefaultDenomModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkModuleState_2 extends _i1.SmartFake
    implements _i4.NetworkModuleState {
  _FakeNetworkModuleState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkModuleBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkModuleBloc extends _i1.Mock implements _i5.NetworkModuleBloc {
  @override
  _i2.Completer<void> get initializationCompleter => (super.noSuchMethod(
        Invocation.getter(#initializationCompleter),
        returnValue: _FakeCompleter_0<void>(
          this,
          Invocation.getter(#initializationCompleter),
        ),
        returnValueForMissingStub: _FakeCompleter_0<void>(
          this,
          Invocation.getter(#initializationCompleter),
        ),
      ) as _i2.Completer<void>);

  @override
  _i3.TokenDefaultDenomModel get tokenDefaultDenomModel => (super.noSuchMethod(
        Invocation.getter(#tokenDefaultDenomModel),
        returnValue: _FakeTokenDefaultDenomModel_1(
          this,
          Invocation.getter(#tokenDefaultDenomModel),
        ),
        returnValueForMissingStub: _FakeTokenDefaultDenomModel_1(
          this,
          Invocation.getter(#tokenDefaultDenomModel),
        ),
      ) as _i3.TokenDefaultDenomModel);

  @override
  set tokenDefaultDenomModel(
          _i3.TokenDefaultDenomModel? _tokenDefaultDenomModel) =>
      super.noSuchMethod(
        Invocation.setter(
          #tokenDefaultDenomModel,
          _tokenDefaultDenomModel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.NetworkModuleState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeNetworkModuleState_2(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeNetworkModuleState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.NetworkModuleState);

  @override
  _i2.Stream<_i4.NetworkModuleState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i2.Stream<_i4.NetworkModuleState>.empty(),
        returnValueForMissingStub: _i2.Stream<_i4.NetworkModuleState>.empty(),
      ) as _i2.Stream<_i4.NetworkModuleState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  void add(_i6.ANetworkModuleEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i6.ANetworkModuleEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i4.NetworkModuleState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i6.ANetworkModuleEvent>(
    _i7.EventHandler<E, _i4.NetworkModuleState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i7.Transition<_i6.ANetworkModuleEvent, _i4.NetworkModuleState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i7.Change<_i4.NetworkModuleState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
