// Mocks generated by Mockito 5.4.4 from annotations
// in miro/test/unit/infra/services/api_kira/query_kira_tokens_aliases_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:miro/config/remote_config.dart' as _i3;
import 'package:miro/infra/dto/api_kira/query_kira_tokens_aliases/response/query_kira_tokens_aliases_resp.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQueryKiraTokensAliasesResp_0 extends _i1.SmartFake
    implements _i2.QueryKiraTokensAliasesResp {
  _FakeQueryKiraTokensAliasesResp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteConfig extends _i1.Mock implements _i3.RemoteConfig {
  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.QueryKiraTokensAliasesResp getAliases() => (super.noSuchMethod(
        Invocation.method(
          #getAliases,
          [],
        ),
        returnValue: _FakeQueryKiraTokensAliasesResp_0(
          this,
          Invocation.method(
            #getAliases,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeQueryKiraTokensAliasesResp_0(
          this,
          Invocation.method(
            #getAliases,
            [],
          ),
        ),
      ) as _i2.QueryKiraTokensAliasesResp);
}
