/// Flutter icons IconsFont
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsFont
///      fonts:
///       - asset: fonts/IconsFont.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const String _kFontFam = 'IconsFont';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consensus = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData proposals = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData validator = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData governance = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deposit = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthy = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receive = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData updown = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData withdraw = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  // ignore: constant_identifier_names
  static const IconData heart_outlined = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hidden = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
