/// Flutter icons IconsFont
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsFont
///      fonts:
///       - asset: fonts/IconsFont.ttf
///
///
///
import 'package:flutter/widgets.dart';

// ignore_for_file: constant_identifier_names
class AppIcons {
  AppIcons._();

  static const String _kFontFam = 'IconsFont';
  static const String? _kFontPkg = null;

  static const IconData account = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_right = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_checked = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_circle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_empty = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consensus = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_circle = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deposit = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_hidden = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_visible = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData governance = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_outlined = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horizontal = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vertical = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData proposals = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_outlined = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transactions = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_down = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verification = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData withdraw = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
