/// Flutter icons App
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  App
///      fonts:
///       - asset: fonts/App.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const String _kFontFam = 'IconsFont';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transaction = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData proposals = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData validator = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData governance = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
