// Mocks generated by Mockito 5.4.4 from annotations
// in miro/test/unit/blocs/generic/metamask_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:flutter_web3/flutter_web3.dart' as _i4;
import 'package:miro/blocs/generic/auth/auth_cubit.dart' as _i6;
import 'package:miro/blocs/generic/identity_registrar/identity_registrar_cubit.dart'
    as _i2;
import 'package:miro/blocs/generic/metamask/ethereum_provider.dart' as _i3;
import 'package:miro/shared/models/wallet/wallet.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIdentityRegistrarCubit_0 extends _i1.SmartFake
    implements _i2.IdentityRegistrarCubit {
  _FakeIdentityRegistrarCubit_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EthereumProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEthereumProvider extends _i1.Mock implements _i3.EthereumProvider {
  @override
  bool get isSupported => (super.noSuchMethod(
        Invocation.getter(#isSupported),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void removeAllListeners() => super.noSuchMethod(
        Invocation.method(
          #removeAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleConnect(void Function(_i4.ConnectInfo)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #handleConnect,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleDisconnect(void Function(_i4.ProviderRpcError)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #handleDisconnect,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleAccountsChanged(void Function(List<String>)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #handleAccountsChanged,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleChainChanged(void Function(int)? listener) => super.noSuchMethod(
        Invocation.method(
          #handleChainChanged,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<String>?> requestAccount() => (super.noSuchMethod(
        Invocation.method(
          #requestAccount,
          [],
        ),
        returnValue: _i5.Future<List<String>?>.value(),
        returnValueForMissingStub: _i5.Future<List<String>?>.value(),
      ) as _i5.Future<List<String>?>);

  @override
  _i5.Future<int?> getChainId() => (super.noSuchMethod(
        Invocation.method(
          #getChainId,
          [],
        ),
        returnValue: _i5.Future<int?>.value(),
        returnValueForMissingStub: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<void> switchWalletChain(int? chainId) => (super.noSuchMethod(
        Invocation.method(
          #switchWalletChain,
          [chainId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addWalletChain({
    required int? chainId,
    required String? rpcUrl,
    required String? chainName,
    required String? nativeCurrencyName,
    required String? nativeCurrencySymbol,
    required int? nativeCurrencyDecimals,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWalletChain,
          [],
          {
            #chainId: chainId,
            #rpcUrl: rpcUrl,
            #chainName: chainName,
            #nativeCurrencyName: nativeCurrencyName,
            #nativeCurrencySymbol: nativeCurrencySymbol,
            #nativeCurrencyDecimals: nativeCurrencyDecimals,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCubit extends _i1.Mock implements _i6.AuthCubit {
  @override
  _i2.IdentityRegistrarCubit get identityRegistrarCubit => (super.noSuchMethod(
        Invocation.getter(#identityRegistrarCubit),
        returnValue: _FakeIdentityRegistrarCubit_0(
          this,
          Invocation.getter(#identityRegistrarCubit),
        ),
        returnValueForMissingStub: _FakeIdentityRegistrarCubit_0(
          this,
          Invocation.getter(#identityRegistrarCubit),
        ),
      ) as _i2.IdentityRegistrarCubit);

  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Stream<_i7.Wallet?> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i7.Wallet?>.empty(),
        returnValueForMissingStub: _i5.Stream<_i7.Wallet?>.empty(),
      ) as _i5.Stream<_i7.Wallet?>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> signIn(_i7.Wallet? wallet) => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [wallet],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void emit(_i7.Wallet? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i8.Change<_i7.Wallet?>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
