// Mocks generated by Mockito 5.4.4 from annotations
// in miro/test/unit/blocs/generic/metamask/metamask_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:flutter_web3/flutter_web3.dart' as _i3;
import 'package:miro/blocs/generic/auth/auth_cubit.dart' as _i8;
import 'package:miro/blocs/generic/metamask/ethereum_provider.dart' as _i2;
import 'package:miro/shared/models/wallet/address/ethereum_wallet_address.dart'
    as _i5;
import 'package:miro/shared/models/wallet/wallet.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EthereumProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEthereumProvider extends _i1.Mock implements _i2.EthereumProvider {
  @override
  bool get isSupported => (super.noSuchMethod(
        Invocation.getter(#isSupported),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void removeAllListeners() => super.noSuchMethod(
        Invocation.method(
          #removeAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleConnect(void Function(_i3.ConnectInfo)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #handleConnect,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleDisconnect(void Function(_i3.ProviderRpcError)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #handleDisconnect,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleAccountsChanged(void Function(List<String>)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #handleAccountsChanged,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleChainChanged(void Function(int)? listener) => super.noSuchMethod(
        Invocation.method(
          #handleChainChanged,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<String>?> requestAccount() => (super.noSuchMethod(
        Invocation.method(
          #requestAccount,
          [],
        ),
        returnValue: _i4.Future<List<String>?>.value(),
        returnValueForMissingStub: _i4.Future<List<String>?>.value(),
      ) as _i4.Future<List<String>?>);

  @override
  _i4.Future<int?> getChainId() => (super.noSuchMethod(
        Invocation.method(
          #getChainId,
          [],
        ),
        returnValue: _i4.Future<int?>.value(),
        returnValueForMissingStub: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<String?> signMessage(
    _i5.EthereumWalletAddress? address,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signMessage,
          [
            address,
            message,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i6.Uint8List convertBits(
    _i6.Uint8List? data,
    int? fromBits,
    int? toBits, {
    bool? pad = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertBits,
          [
            data,
            fromBits,
            toBits,
          ],
          {#pad: pad},
        ),
        returnValue: _i6.Uint8List(0),
        returnValueForMissingStub: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  String ethereumPublicKeyToCosmosAddress(
    _i6.Uint8List? publicKey,
    String? prefix,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #ethereumPublicKeyToCosmosAddress,
          [
            publicKey,
            prefix,
          ],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #ethereumPublicKeyToCosmosAddress,
            [
              publicKey,
              prefix,
            ],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #ethereumPublicKeyToCosmosAddress,
            [
              publicKey,
              prefix,
            ],
          ),
        ),
      ) as String);

  @override
  _i4.Future<void> getPublicKey() => (super.noSuchMethod(
        Invocation.method(
          #getPublicKey,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i6.Uint8List? recoverPublicKeyFromSignature(
    String? signature,
    _i6.Uint8List? msgHash,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverPublicKeyFromSignature,
          [
            signature,
            msgHash,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i6.Uint8List?);

  @override
  _i6.Uint8List ethereumPublicKeyFromHex(String? publicKeyHex) =>
      (super.noSuchMethod(
        Invocation.method(
          #ethereumPublicKeyFromHex,
          [publicKeyHex],
        ),
        returnValue: _i6.Uint8List(0),
        returnValueForMissingStub: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  _i4.Future<Map<String, dynamic>?> signTransaction(
    String? userAddress,
    Map<String, dynamic>? transaction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signTransaction,
          [
            userAddress,
            transaction,
          ],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i6.Uint8List extractRSV(String? signature) => (super.noSuchMethod(
        Invocation.method(
          #extractRSV,
          [signature],
        ),
        returnValue: _i6.Uint8List(0),
        returnValueForMissingStub: _i6.Uint8List(0),
      ) as _i6.Uint8List);

  @override
  Map<String, dynamic> buildSignedCosmosTx(
    String? pubKeyBase64,
    String? signatureBase64, {
    required Map<String, dynamic>? fee,
    required List<Map<String, dynamic>>? msg,
    required int? r,
    required int? s,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildSignedCosmosTx,
          [
            pubKeyBase64,
            signatureBase64,
          ],
          {
            #fee: fee,
            #msg: msg,
            #r: r,
            #s: s,
          },
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> switchWalletChain(int? chainId) => (super.noSuchMethod(
        Invocation.method(
          #switchWalletChain,
          [chainId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addWalletChain({
    required int? chainId,
    required String? rpcUrl,
    required String? chainName,
    required String? nativeCurrencyName,
    required String? nativeCurrencySymbol,
    required int? nativeCurrencyDecimals,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWalletChain,
          [],
          {
            #chainId: chainId,
            #rpcUrl: rpcUrl,
            #chainName: chainName,
            #nativeCurrencyName: nativeCurrencyName,
            #nativeCurrencySymbol: nativeCurrencySymbol,
            #nativeCurrencyDecimals: nativeCurrencyDecimals,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCubit extends _i1.Mock implements _i8.AuthCubit {
  @override
  bool get isEthereumSession => (super.noSuchMethod(
        Invocation.getter(#isEthereumSession),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<_i9.Wallet?> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i9.Wallet?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i9.Wallet?>.empty(),
      ) as _i4.Stream<_i9.Wallet?>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> signIn(
    _i9.Wallet? wallet, {
    bool? defaultAddressIsKiraBool = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [wallet],
          {#defaultAddressIsKiraBool: defaultAddressIsKiraBool},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void toggleWalletAddress() => super.noSuchMethod(
        Invocation.method(
          #toggleWalletAddress,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i9.Wallet? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i10.Change<_i9.Wallet?>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
