// Mocks generated by Mockito 5.4.4 from annotations
// in miro/test/unit/blocs/generic/auth_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i14;

import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:flutter_web3/flutter_web3.dart' as _i13;
import 'package:miro/blocs/generic/auth/auth_cubit.dart' as _i4;
import 'package:miro/blocs/generic/identity_registrar/a_identity_registrar_state.dart'
    as _i3;
import 'package:miro/blocs/generic/identity_registrar/identity_registrar_cubit.dart'
    as _i10;
import 'package:miro/blocs/generic/metamask/ethereum_provider.dart' as _i12;
import 'package:miro/infra/managers/cache/impl/hive_cache_manager.dart' as _i15;
import 'package:miro/shared/controllers/page_reload/page_reload_controller.dart'
    as _i2;
import 'package:miro/shared/models/wallet/address/a_wallet_address.dart' as _i7;
import 'package:miro/shared/models/wallet/address/cosmos_wallet_address.dart'
    as _i11;
import 'package:miro/shared/models/wallet/wallet.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePageReloadController_0 extends _i1.SmartFake
    implements _i2.PageReloadController {
  _FakePageReloadController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAIdentityRegistrarState_1 extends _i1.SmartFake
    implements _i3.AIdentityRegistrarState {
  _FakeAIdentityRegistrarState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCubit extends _i1.Mock implements _i4.AuthCubit {
  @override
  bool get isEthereumSession => (super.noSuchMethod(
        Invocation.getter(#isEthereumSession),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Stream<_i6.Wallet?> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i6.Wallet?>.empty(),
        returnValueForMissingStub: _i5.Stream<_i6.Wallet?>.empty(),
      ) as _i5.Stream<_i6.Wallet?>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> signIn(
    _i6.Wallet? wallet, {
    bool? defaultAddressIsKiraBool = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [wallet],
          {#defaultAddressIsKiraBool: defaultAddressIsKiraBool},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i7.AWalletAddress? tryFindOppositeAddress(_i7.AWalletAddress? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #tryFindOppositeAddress,
          [address],
        ),
        returnValueForMissingStub: null,
      ) as _i7.AWalletAddress?);

  @override
  String replaceAddressTypeIfExists(
    String? address, {
    String? delimiter = r' ',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAddressTypeIfExists,
          [address],
          {#delimiter: delimiter},
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #replaceAddressTypeIfExists,
            [address],
            {#delimiter: delimiter},
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #replaceAddressTypeIfExists,
            [address],
            {#delimiter: delimiter},
          ),
        ),
      ) as String);

  @override
  void toggleWalletAddress() => super.noSuchMethod(
        Invocation.method(
          #toggleWalletAddress,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i6.Wallet? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i9.Change<_i6.Wallet?>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [IdentityRegistrarCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdentityRegistrarCubit extends _i1.Mock
    implements _i10.IdentityRegistrarCubit {
  @override
  _i2.PageReloadController get pageReloadController => (super.noSuchMethod(
        Invocation.getter(#pageReloadController),
        returnValue: _FakePageReloadController_0(
          this,
          Invocation.getter(#pageReloadController),
        ),
        returnValueForMissingStub: _FakePageReloadController_0(
          this,
          Invocation.getter(#pageReloadController),
        ),
      ) as _i2.PageReloadController);

  @override
  set walletAddress(_i11.CosmosWalletAddress? _walletAddress) =>
      super.noSuchMethod(
        Invocation.setter(
          #walletAddress,
          _walletAddress,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AIdentityRegistrarState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAIdentityRegistrarState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeAIdentityRegistrarState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AIdentityRegistrarState);

  @override
  _i5.Stream<_i3.AIdentityRegistrarState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i3.AIdentityRegistrarState>.empty(),
        returnValueForMissingStub:
            _i5.Stream<_i3.AIdentityRegistrarState>.empty(),
      ) as _i5.Stream<_i3.AIdentityRegistrarState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setWalletAddress(_i11.CosmosWalletAddress? walletAddress) =>
      (super.noSuchMethod(
        Invocation.method(
          #setWalletAddress,
          [walletAddress],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> refresh({bool? forceRequestBool = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
          {#forceRequestBool: forceRequestBool},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void emit(_i3.AIdentityRegistrarState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i9.Change<_i3.AIdentityRegistrarState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EthereumProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockEthereumProvider extends _i1.Mock implements _i12.EthereumProvider {
  @override
  bool get isSupported => (super.noSuchMethod(
        Invocation.getter(#isSupported),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void removeAllListeners() => super.noSuchMethod(
        Invocation.method(
          #removeAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleConnect(void Function(_i13.ConnectInfo)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #handleConnect,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleDisconnect(void Function(_i13.ProviderRpcError)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #handleDisconnect,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleAccountsChanged(void Function(List<String>)? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #handleAccountsChanged,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleChainChanged(void Function(int)? listener) => super.noSuchMethod(
        Invocation.method(
          #handleChainChanged,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<String>?> requestAccount() => (super.noSuchMethod(
        Invocation.method(
          #requestAccount,
          [],
        ),
        returnValue: _i5.Future<List<String>?>.value(),
        returnValueForMissingStub: _i5.Future<List<String>?>.value(),
      ) as _i5.Future<List<String>?>);

  @override
  _i5.Future<int?> getChainId() => (super.noSuchMethod(
        Invocation.method(
          #getChainId,
          [],
        ),
        returnValue: _i5.Future<int?>.value(),
        returnValueForMissingStub: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<String?> getPublicKey(String? address) => (super.noSuchMethod(
        Invocation.method(
          #getPublicKey,
          [address],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<String?> signMessage(
    String? address,
    String? message,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signMessage,
          [
            address,
            message,
          ],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<_i12.EthereumSignatureDecodeResult?> decodeEthereumSignature({
    required String? message,
    required String? signatureHex,
    required String? ethereumAddress,
    required String? bech32Hrp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decodeEthereumSignature,
          [],
          {
            #message: message,
            #signatureHex: signatureHex,
            #ethereumAddress: ethereumAddress,
            #bech32Hrp: bech32Hrp,
          },
        ),
        returnValue: _i5.Future<_i12.EthereumSignatureDecodeResult?>.value(),
        returnValueForMissingStub:
            _i5.Future<_i12.EthereumSignatureDecodeResult?>.value(),
      ) as _i5.Future<_i12.EthereumSignatureDecodeResult?>);

  @override
  _i14.Uint8List compressPublicKey(_i14.Uint8List? uncompressedPublicKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #compressPublicKey,
          [uncompressedPublicKey],
        ),
        returnValue: _i14.Uint8List(0),
        returnValueForMissingStub: _i14.Uint8List(0),
      ) as _i14.Uint8List);

  @override
  String convertPublicKeyToCosmosAddress(
    _i14.Uint8List? publicKey,
    String? humanReadablePart,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertPublicKeyToCosmosAddress,
          [
            publicKey,
            humanReadablePart,
          ],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #convertPublicKeyToCosmosAddress,
            [
              publicKey,
              humanReadablePart,
            ],
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #convertPublicKeyToCosmosAddress,
            [
              publicKey,
              humanReadablePart,
            ],
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> switchWalletChain(int? chainId) => (super.noSuchMethod(
        Invocation.method(
          #switchWalletChain,
          [chainId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addWalletChain({
    required int? chainId,
    required String? rpcUrl,
    required String? chainName,
    required String? nativeCurrencyName,
    required String? nativeCurrencySymbol,
    required int? nativeCurrencyDecimals,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWalletChain,
          [],
          {
            #chainId: chainId,
            #rpcUrl: rpcUrl,
            #chainName: chainName,
            #nativeCurrencyName: nativeCurrencyName,
            #nativeCurrencySymbol: nativeCurrencySymbol,
            #nativeCurrencyDecimals: nativeCurrencyDecimals,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [HiveCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockICacheManager extends _i1.Mock implements _i15.HiveCacheManager {
  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> add<T>({
    required String? boxName,
    required String? key,
    required T? value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #add,
          [],
          {
            #boxName: boxName,
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> delete<T>({
    required String? boxName,
    required String? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #boxName: boxName,
            #key: key,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAll<T>({required String? boxName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {#boxName: boxName},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  T get<T>({
    required String? boxName,
    required String? key,
    required T? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
          {
            #boxName: boxName,
            #key: key,
            #defaultValue: defaultValue,
          },
        ),
        returnValue: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #get,
            [],
            {
              #boxName: boxName,
              #key: key,
              #defaultValue: defaultValue,
            },
          ),
        ),
        returnValueForMissingStub: _i8.dummyValue<T>(
          this,
          Invocation.method(
            #get,
            [],
            {
              #boxName: boxName,
              #key: key,
              #defaultValue: defaultValue,
            },
          ),
        ),
      ) as T);

  @override
  Map<String, T> getAll<T>({required String? boxName}) => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
          {#boxName: boxName},
        ),
        returnValue: <String, T>{},
        returnValueForMissingStub: <String, T>{},
      ) as Map<String, T>);
}
